name: Pull Request Checks

on: [pull_request]

jobs:
  linting-and-testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.19'
          stable: true

      - name: Cache Go Modules
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Tidy Modules
        run: go mod tidy

      - name: Build the provider
        run: go build -o terraform-provider-kong

      - name: Generate Docs
        run: go generate ./...

      - name: Run Unit Tests
        run: make unit-test

      # Uncomment once you have acceptance tests set up and you want them to run on PR checks
      # - name: Run Acceptance Tests
      #   run: make acceptance-test
